
============= Initialized Observation Utils with Obs Spec =============

using obs modality: low_dim with keys: ['object']
using obs modality: rgb with keys: []
using obs modality: depth with keys: []
using obs modality: scan with keys: []

============= Loaded Environment Metadata =============
run failed with error:
[Errno 21] Unable to open file (file read failed: time = Sun Apr  9 19:38:53 2023
, filename = 'datasets/lift', file descriptor = 5, errno = 21, error message = 'Is a directory', buf = 0x7ffcf8e8d4e8, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

Traceback (most recent call last):
  File "robomimic/scripts/train.py", line 355, in main
    train(config, device=device)
  File "robomimic/scripts/train.py", line 75, in train
    env_meta = FileUtils.get_env_metadata_from_dataset(dataset_path=config.train.data)
  File "/home/palash/robomimic/robomimic/utils/file_utils.py", line 81, in get_env_metadata_from_dataset
    f = h5py.File(dataset_path, "r")
  File "/home/palash/anaconda3/envs/robomimic_venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/palash/anaconda3/envs/robomimic_venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
IsADirectoryError: [Errno 21] Unable to open file (file read failed: time = Sun Apr  9 19:38:53 2023
, filename = 'datasets/lift', file descriptor = 5, errno = 21, error message = 'Is a directory', buf = 0x7ffcf8e8d4e8, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

